export const ADD_USER = 'ADD_USER'
export const DEL_USER = 'DEL_USER'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'
export const CHANGE_TOKEN = "CHANGE_TOKEN"
export const CLEAR_TOKEN = "CLEAR_TOKEN"